# Generated by Django 3.1 on 2022-03-04 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('ram', models.IntegerField(max_length=3)),
                ('hard_disk', models.IntegerField(max_length=10)),
                ('processor_speed', models.FloatField(max_length=5)),
                ('additional_properties', models.TextField(max_length=400)),
                ('phone', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(message='phone number must be entered in the format 09xxxxxxxx or +2519xxxxxxxx', regex='^(09)\\d{8}$|^(+251)\\d{9}$')])),
                ('status', models.CharField(blank=True, choices=[(1, 'new'), (2, 'slightlyused'), (3, 'used')], max_length=30)),
                ('screen_size', models.CharField(blank=True, choices=[(1, '11.6 inch'), (2, '12.5 inch'), (3, '13.3 inch'), (4, '14 inch'), (5, '15.6 inch'), (5, '17.3 inch')], max_length=10)),
                ('core', models.CharField(choices=[(1, 'i3'), (2, 'i5'), (3, 'i7')], max_length=2)),
            ],
        ),
    ]
