# Generated by Django 3.1 on 2022-03-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerspecification',
            name='hard_disk',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='computerspecification',
            name='processor_speed',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='computerspecification',
            name='ram',
            field=models.IntegerField(),
        ),
    ]
