# Generated by Django 3.1 on 2022-03-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0002_auto_20220304_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerspecification',
            name='photo',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
