# Generated by Django 3.1 on 2022-03-06 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0003_computerspecification_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerspecification',
            name='price',
            field=models.CharField(default=15000, help_text='inter the price in 15000 format', max_length=10, validators=[django.core.validators.RegexValidator(message='Enter amount in number', regex='^\\d$')]),
        ),
        migrations.AlterField(
            model_name='computerspecification',
            name='additional_properties',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='computerspecification',
            name='core',
            field=models.CharField(choices=[('i3', 'i3'), ('i5', 'i5'), ('i7', 'i7'), ('i9', 'i9')], max_length=2),
        ),
        migrations.AlterField(
            model_name='computerspecification',
            name='hard_disk',
            field=models.CharField(choices=[('16 GB', '16 GB'), ('32 GB', '32 GB'), ('64 GB', '64 GB'), ('128 GB', '128 GB'), ('256 GB', '256 GB'), ('500 GB', '500 GB'), ('1 TB ', '1 TB/ 1000 GB'), ('1.5 TB ', '1.5 TB/ 1500 GB'), ('2 TB ', '2 TB/ 2000GB'), ('4 TB ', '4 TB/ 4000GB'), ('6 TB ', '6 TB/ 6000GB'), ('8 TB ', '8 TB/ 8000GB')], max_length=10),
        ),
        migrations.AlterField(
            model_name='computerspecification',
            name='phone',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(message='phone number must be entered in the format 09xxxxxxxx or +2519xxxxxxxx', regex='^\\+?\\d{10,12}$')]),
        ),
        migrations.AlterField(
            model_name='computerspecification',
            name='processor_speed',
            field=models.CharField(help_text='the value must in 5.6 GHz format', max_length=7, validators=[django.core.validators.RegexValidator(message='the value must be in 5.6 GHz format', regex='^\\d?\\.\\d\\s(GHz)')]),
        ),
        migrations.AlterField(
            model_name='computerspecification',
            name='ram',
            field=models.CharField(choices=[('LESS THAN 1GB', '<1 GB'), ('1 GB', '1 GB'), ('2 GB', '2 GB'), ('4 GB', '4 GB'), ('8 GB', '8 GB'), ('12 GB', '12 GB'), ('GREATER THAN 16 GB', '>16 GB')], max_length=30),
        ),
        migrations.AlterField(
            model_name='computerspecification',
            name='screen_size',
            field=models.CharField(choices=[('11.6 inch', '11.6 inch'), ('12.5 inch', '12.5 inch'), ('13.3 inch', '13.3 inch'), ('14 inch', '14 inch'), ('15.6 inch', '15.6 inch'), ('17.3 inch', '17.3 inch')], max_length=10),
        ),
        migrations.AlterField(
            model_name='computerspecification',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('slightly used', 'slightlyused'), ('used', 'used')], max_length=30),
        ),
    ]
