# Generated by Django 3.1 on 2022-03-06 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0004_auto_20220306_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerspecification',
            name='price',
            field=models.CharField(default=15000, help_text='inter the price in 15000 format', max_length=10, validators=[django.core.validators.RegexValidator(message='Enter amount in number', regex='^\\d')]),
        ),
        migrations.AlterField(
            model_name='computerspecification',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('slightly used', 'slightly used'), ('used', 'used')], max_length=30),
        ),
    ]
