# Generated by Django 3.1 on 2022-03-06 23:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0005_auto_20220306_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerspecification',
            name='phone2',
            field=models.CharField(blank=True, help_text='optional', max_length=40, null=True, validators=[django.core.validators.RegexValidator(message='phone number must be entered in the format 09xxxxxxxx or +2519xxxxxxxx', regex='^\\+?\\d{10,12}$')]),
        ),
    ]
