# Generated by Django 3.1 on 2022-03-06 23:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0006_computerspecification_phone2'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerspecification',
            name='battery_life',
            field=models.CharField(default='2.5 hr', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter in 5.6 hr form', regex='^\\d\\.\\d\\s(hr)')]),
        ),
    ]
