# Generated by Django 3.1 on 2022-03-07 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0007_computerspecification_battery_life'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computerspecification',
            old_name='additional_properties',
            new_name='description',
        ),
    ]
